# Generated by Django 4.1.5 on 2023-01-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container', models.CharField(max_length=15)),
                ('unidade', models.CharField(choices=[('20', "20'"), ('40', "40'")], max_length=2)),
                ('tipo', models.CharField(choices=[('DRY', 'DRY'), ('FR', 'FLAT RACK'), ('HC', 'HC'), ('OT', 'OPEN TOP'), ('TK', 'TANK'), ('RF', 'REEFER')], max_length=3)),
                ('lacre', models.CharField(max_length=30)),
                ('modal', models.CharField(choices=[('I', 'Importação'), ('E', 'Exportação')], max_length=1)),
                ('estado', models.CharField(choices=[('C', 'Cheio'), ('V', 'Vazio')], max_length=1)),
            ],
        ),
    ]
