# Generated by Django 4.1.5 on 2023-01-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mov_ctn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentos',
            name='data_alteracao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='movimentos',
            name='data_entrada',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='movimentos',
            name='data_saida',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='movimentos',
            name='observ',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movimentos',
            name='usuario_alteracao',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movimentos',
            name='usuario_inclusao',
            field=models.IntegerField(null=True),
        ),
    ]
