# Generated by Django 4.1.5 on 2023-01-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mov_ctn', '0004_alter_movimentos_observ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentos',
            name='data_entrada',
            field=models.DateField(),
        ),
    ]
