# Generated by Django 4.1.5 on 2023-01-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mov_ctn', '0005_alter_movimentos_data_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentos',
            name='data_entrada',
            field=models.DateTimeField(),
        ),
    ]
