# Generated by Django 4.1.5 on 2023-01-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mov_ctn', '0006_alter_movimentos_data_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentos',
            name='data_saida',
            field=models.DateTimeField(null=True),
        ),
    ]
