# Generated by Django 4.1.5 on 2023-01-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mov_ctn', '0007_alter_movimentos_data_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentos',
            name='usuario_inclusao',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
