# Generated by Django 4.1.5 on 2023-01-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mov_ctn', '0008_alter_movimentos_usuario_inclusao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentos',
            name='usuario_alteracao',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
